version: "3.8"

services:

  app:
    image: facturacion-app
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=jwt
      - DB_USER=root
      - DB_PASSWORD=Phpstorm2020
    restart: always

  db:
    image: mysql:8
    container_name: mysql_facturacion
    environment:
      MYSQL_ROOT_PASSWORD: Phpstorm2020
      MYSQL_DATABASE: jwt
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
